export const colors = {
  bgMain: '#13151e',
  bgPanel: '#1a1d28',
  bgCanvas: '#0d0f16',
  bgInput: '#222638',
  bgSection: '#1e2130',
  bgHover: '#282d3e',
  bgActive: '#1a2a22',
  accent: '#00ff88',
  accentDim: '#00cc6e',
  accentOrange: '#ff8c42',
  orange: '#ff8c42',
  warning: '#ff8c42',
  danger: '#ff5c6c',
  red: '#ff5c6c',
  yellow: '#ffd166',
  textPrimary: '#ffffff',
  textSecondary: '#ffffff',
  textHint: '#ffffff',
  textValue: '#ffffff',
  border: '#2e3348',
  borderInput: '#3a4058',
  borderFocus: '#00ff88',
} as const

export const fonts = {
  family: "'Inter', system-ui, -apple-system, sans-serif",
  familyMono: "'JetBrains Mono', 'Fira Code', 'Consolas', monospace",
  sizeLabel: '13px',
  sizeInput: '16px',
  sizeHeading: '14px',
  sizeHint: '13px',
} as const
